### ISSUE TITLE
Win32: ruby 2.2 - dl has been removed

### ISSUE THREAD

**Issue by janahanEDH** [ai/r18n#125]
In ruby 2.2.2 (win32), the DL module has been removed in favor of Fiddle. R18n-Desktop is still using DL and, therefore, no longer works.

Steps to reproduce:
* Find a Windows 7/8 system.
* Install ruby 2.2.2 (I use the 32-bit version) from http://rubyinstaller.org/downloads/
* gem install r18n-desktop
* start IRB
* require 'r18n-desktop'

You should see:
LoadError: cannot load such file -- dl/import
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/r18n-desktop-2.0.3/lib/r18n-desktop/win32.rb:20:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/r18n-desktop-2.0.3/lib/r18n-desktop.rb:25:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from C:/Ruby22/bin/irb:11:in `<main>'

**Comment by ai** [comment]
Sorry, I totally have no skills to fix it. Can youu helps me?

**Comment by janahanEDH** [comment]
Sure, it's just a 2-line change.
Edit the "r18n-desktop/lib/r18n-desktop/win32.rb" file
Change line 20 to: require 'fiddle/import'
Change line 25 to: extend Fiddle::Importer

**Comment by ai** [comment]
Awesome!

Can I ask you to send PR? It will be better for project history.

Also you will be able to test fixes in Windows.

**Comment by janahanEDH** [comment]
https://github.com/ai/r18n/pull/126

**Comment by ai** [comment]
Released in 2.0.4
