### ISSUE TITLE
?locale=&v=1, if params[:locale] will return true??

### ISSUE THREAD

**Issue by luoguanzhong** [ai/r18n#128]
I use `sinatra-r18n-2.0.4`, the code:

```
locales = ::R18n::I18n.parse_http(request.env['HTTP_ACCEPT_LANGUAGE'])
if params[:locale]
  locales.insert(0, params[:locale])
elsif session[:locale]
  locales.insert(0, session[:locale])
end
```

When the request url `?locale=&v=1`, the code `locales.insert(0, params[:locale])` also be invoked.

@ai, excuse me, but  what's the situation?

**Comment by ai** [comment]
Yeap, it is issue. Please send a PR, I will release a fix.

**Comment by ai** [comment]
Seems like it do not produce any problem f8faa6c
