### ISSUE TITLE
can't convert R18n::TranslatedString to Array

### ISSUE THREAD

**Issue by philest** [ai/r18n#129]
Calling `R18n.t.help.normal("Tues & Thurs")` and `R18n.t.help.sprint("Tues & Thurs")`

with the yaml file: 

    en.yml

    help:
      normal: "We send messages on %1."
      sprint:  "We only send messages on %1."

gives this error: 

`can't convert R18n::TranslatedString to Array (R18n::TranslatedString#to_ary gives R18n::Untranslated)`

Any ideas?

**Comment by ai** [comment]
Try `R18n.t.help.normal("Tues & Thurs")` in `irb` (do not forget to load translations before). Seems like it is confict between your template engine and R18n.

**Comment by philest** [comment]
That works completely find, which is the strange part. 

I'm using sinatra-r18n. Is it possible this has something to do with rspec?

**Comment by ai** [comment]
Can you show where did you use this translations.

Also try this:

```ruby
R18n.t.help.normal("Tues & Thurs").to_s
```

**Comment by philest** [comment]
Ah, beautiful- it works.

The problems seemed to comes as I passed the R18n::Translated Object to a testing wrapper that would pass the object along to Rspec to make sure the response was correct.
