### ISSUE TITLE
Manually changing locale more than once 

### ISSUE THREAD

**Issue by philest** [ai/r18n#130]
In my first unit test, I have `R18n.set 'en'`.

In my next unit test, the current locale is en. I then try to manually change the locale: `R18n.set 'es'`

But the locale is unchanged and still en.

Any ideas here? And thanks for the help.

**Comment by philest** [comment]
I see the method R18n.change for temporary locale changes, but this doesn't seem to be updating the *current* locale, as returned by R18n.get.locale.

How might I update this?

**Comment by ai** [comment]
What environment you use to run R18n? Sinatra R18n?

**Comment by philest** [comment]
Yes, Sinatra R18n

**Comment by ai** [comment]
Can you show me a test?

**Comment by ai** [comment]
Sinatra has separated I18n object in each Thread https://github.com/ai/r18n/blob/master/sinatra-r18n/lib/sinatra/r18n.rb#L35

**Comment by ai** [comment]
So try to use `R18n.thread_set`

**Comment by philest** [comment]
I'm using rspec for testing. 

Here are the two tests. In the seconds, it doesn't change the locale (I've tried with both set and change).


```
it "properly sends the no_signup_match message" do
  get '/test/555/' 
  R18n.set :en
  expect(R18n.t.error.no_signup_match).to_not eq nil
````

```
it "For es locale, sends two messages, not one" do
    R18n.change :es
   expect(Helpers.getSMSarr.length).to eq 2
   #here's the error: it's still in the :en locale
```

**Comment by philest** [comment]
How would I use `R18n.thread_set` in this situation? When I try `R18n.thread_set 'es'`, I get `       undefined method `t' for "es":String`

**Comment by ai** [comment]
Try

```ruby
i18n = R18n::I18n.new(locales, ::R18n.default_places)
R18n.thread_set(i18n);
```

**Comment by philest** [comment]
Great!-- this works.

Any chance you could explain the magic under the hood or point me toward
relevant documentation?

-Phi

**Comment by ai** [comment]
R18n is not really supported right now (as my any other Ruby projects), to change docs for this cases :)
