### ISSUE TITLE
The TranslatedString#to_s now returns nil some cases

### ISSUE THREAD

**Issue by raxoft** [ai/r18n#136]
The commit 2e54394c2492e0c4ac22c100cead46c4f8467298 introduced some bugs.

First of all, I believe `TranslatedString#to_s` should check if the `@value` responds to `html_safe`, not self.

More important thing however is that now `to_s` doesn't work at all in some cases. Before, code like this was working fine for translated strings:

``` ruby
puts text.split("\n").first.to_s.encoding
```

Now it fails (with undefined method `encoding` for `nil:NilClass` error). The reason is that `split` creates array of `TranslatedString`s, none of which however have the `@value` set. Cloning the class of the actual string itself seems to be a feature of `split`, but it obviously causes mismatch between the value of the string itself and the `@value` variable, which is now lacking (not to mention the lack of other instance variables, but it's not much of an problem for me).

I believe other String operations might suffer from the same problem, so it might be best to drop the `@value` idea entirely and base the value of the string solely on the string itself.

**Comment by raxoft** [comment]
BTW, the `split` behaviour can be easily tested with this snippet:

``` ruby
class C < String
end

p C.new("test").split("t").map{ |x| [x.class, x] }
```

Other string methods really seem to share this class cloning behaviour, such as `scan`.

**Comment by raxoft** [comment]
BTW, testing the mentioned commit a bit further, it also seems that the conversion of value to string added to the beginning of `TranslatedString#initialize` handles only `TranslatedString`, but not `Untranslated` strings. As a consequence, calling `to_s` on `Untranslated` string now returns `TranslatedString`, rather than `String` as expected.

**Comment by raxoft** [comment]
And while we are at it, the change at translation.rb:96 from `@filters` to `@filter` looks just like a typo - there is no `@filter` instance variable in the `Translation` class.

**Comment by ai** [comment]
Thanks for really good investigation. I will look closer on this week.

**Comment by raxoft** [comment]
Hello, sorry for the bump, but is there any chance to get this fixed? Alternatively, I can try to create a patch myself. Just one question - do you remember what was the idea behind introducing @value instead of using self as before? Thanks.

**Comment by ai** [comment]
Yeap, PR will be very welcome

**Comment by raxoft** [comment]
OK, I will have a look. Is support for 2.2+ enough or shall I aim for 2.1 as well?

**Comment by ai** [comment]
2.1 support will be good, because I need a major release to drop 2.1 support.

**Comment by raxoft** [comment]
OK, the PR is ready in #147.
