### ISSUE TITLE
ActiveSupport::JSON.encode fails in ruby 2.3.x

### ISSUE THREAD

**Issue by creddy** [ai/r18n#139]
##### Description

In Ruby 2.2.4 ActiveSupport::JSON.encode works with R18n::TranslatedString, but in 2.3.2 it fails. This shows up in our Rails app when we are attempting to render an object that contains translated strings to JSON. 

For repro code, please see the repo [here](https://github.com/creddy/r18n-ruby-2-3)

```ruby 
require "r18n-core"
require "active_support"

R18n.default_places = 'translations'
R18n.set('en')

include R18n::Helpers

puts ActiveSupport::JSON.encode(t.foobar)
```

##### Expected 

➜  r18n-ruby-2-3 [2.2.4] (master) ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin16]
➜  r18n-ruby-2-3 [2.2.4] (master) rake
"foobar translated"

##### Actual

➜  r18n-ruby-2-3 [2.3.2] (master) ruby -v
ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]
➜  r18n-ruby-2-3 [2.3.2] (master) rake
rake aborted!
TypeError: can't convert R18n::TranslatedString to Hash (R18n::TranslatedString#to_hash gives R18n::Untranslated)
test.rb:9:in `<top (required)>'

Thank you

**Comment by ai** [comment]
@creddy Hi. Thanks for very good issue report.

Could you thy this fix:

```ruby
class R18n::TranslatedString
  def to_hash
    return to_s
  end
end
```

**Comment by creddy** [comment]
Hello @ai. You're welcome, I'm happy to help. 

Here are the results

```
➜  r18n-ruby-2-3 [2.3.2] (master) ✗ ruby -v
ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]
➜  r18n-ruby-2-3 [2.3.2] (master) ✗ cat test.rb
require "r18n-core"
require "active_support"

class R18n::TranslatedString
  def to_hash
    return to_s
  end
end

R18n.default_places = 'translations'
R18n.set('en')

include R18n::Helpers

puts ActiveSupport::JSON.encode(t.foobar)
➜  r18n-ruby-2-3 [2.3.2] (master) ✗ rake
rake aborted!
TypeError: can't convert R18n::TranslatedString to Hash (R18n::TranslatedString#to_hash gives String)
test.rb:15:in `<top (required)>'
```

**Comment by ai** [comment]
Sorry, I lost ,y self in other open source project :).

Could you just use:

```rb
ActiveSupport::JSON.encode(t.foobar.to_s)
```

**Comment by creddy** [comment]
No worries :)

Here is the result

```
➜  r18n-ruby-2-3 [2.3.2] (master) ✗ ruby -v
ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]
➜  r18n-ruby-2-3 [2.3.2] (master) ✗ cat test.rb
require "r18n-core"
require "active_support"

R18n.default_places = 'translations'
R18n.set('en')

include R18n::Helpers

puts ActiveSupport::JSON.encode(t.foobar.to_s)
➜  r18n-ruby-2-3 [2.3.2] (master) ✗ rake
"foobar translated"
```
