### ISSUE TITLE
Markdown purpose

### ISSUE THREAD

**Issue by AlexWayfer** [ai/r18n#145]
Hello!

I'm using Markdown strings in YAML files instead of HTML for flexibility: I can render them as HTML, or maybe JSON, or anything else (maybe it's a little crazy). With manual post-processing.

But today I saw built-in filter `!!markdown` (via `kramdown` by default), and hard-coded `Kramdown::Document#to_html`.

So, my question is: than using `!!markdown` is better than HTML tags in translation strings?

**Comment by ai** [comment]
If you need HTML tags only, you don’t need `!!markdown` (at least, it will be slower).

**Comment by AlexWayfer** [comment]
But… how I can get non-HTML output?

**Comment by ai** [comment]
Define your own filter.

**Comment by AlexWayfer** [comment]
Can I define filter with arguments? Or can I redefine `markdown` filter only in the current thread?

**Comment by AlexWayfer** [comment]
Oh… Or maybe I must define filter with internal switching by something global (variable/constant)… Okay…

**Comment by AlexWayfer** [comment]
@ai Stop. If I have two controllers, for example, which should processing markdown differently - how can I write a condition in my filter, defined once? There are no arguments for filters or anything else helpful.

**Comment by ai** [comment]
@AlexWayfer in this case, don’t use Markdown in R18n.

```ruby
source = t.body
if request.html?
  markdown_to_html(source)
else
  markdown_to_json(source)
end
```

**Comment by AlexWayfer** [comment]
@ai Well, thank you.

Going back to the original question: why, then, does the built-in `markdown` filter? Why is it better than embedded HTML tags? The ability to redefine it?

**Comment by ai** [comment]
@AlexWayfer `markdown` filter is good, when you need to have HTML in messages, but you want to keep readability. `Name is *%1*` is more readable than `Name is <strong>%1</strong>`

**Comment by AlexWayfer** [comment]
Finally, thank you!

I thought about it, I was just afraid that I did not know of any other advantages or purposes.

I have no more questions about this.
