### ISSUE TITLE
Raise an exception when hitting an untranslated string?

### ISSUE THREAD

**Issue by mkaito** [ai/r18n#148]
Hi!

I'd like my integration tests to catch any untranslated interface elements. I think the easiest way would be to have R18n raise an exception instead of filling in the red default text.

**Comment by ai** [comment]
I can't change default behavior.

But you can change default behavior in your app. Untranslated is generated by filter.

If you need I can show how to do it tomorrow.

**Comment by mkaito** [comment]
I'd appreciate that, thanks.

Quoting Andrey Sitnik (2017-06-09 01:45:12)

**Comment by ai** [comment]
Here is current `Untranslated` filters: https://github.com/ai/r18n/blob/master/r18n-core/lib/r18n-core/filters.rb#L247-L267

By default `:untranslated_bash` and `:untrasnlated_html` switched off, but `sinatra-r18n` and `rails-r18n` should enable it https://github.com/ai/r18n/blob/master/r18n-rails/lib/r18n-rails/controller.rb#L41-L42

So you need:

```ruby
  Filters.add(Untranslated, :untranslated_raise) do |v, c, transl, untransl|
    raise "No translation in #{ untransl }"
  end
```
