### ISSUE TITLE
Translations in DB

### ISSUE THREAD

**Issue by mkaito** [ai/r18n#155]
Hi!

I saw the sparse example in the readme about using ActiveRecord as storage backend. I don't suppose you could expand on that?

For example, what columns would the database table need to have?

**Comment by ai** [comment]
`#{ field }_#{ locale }`. I will update docs

**Comment by ai** [comment]
We already have docs about it https://github.com/ai/r18n/tree/master/r18n-core#model

Do you know how improve them?

**Comment by AlexWayfer** [comment]
@ai, perhaps @mkaito asked about [`DBLoader`](https://github.com/ai/r18n#total-flexibility).

**Comment by ai** [comment]
Ouh. We didn’t have it. It is just a example, what *you* can do ;)

**Comment by mkaito** [comment]
Yes, I meant DBLoader.

El 16 de octubre de 2017 19:12:24 GMT+01:00, Alexander Popov <notifications@github.com> escribió:
>@ai, perhaps @mkaito asked about
>[`DBLoader`](https://github.com/ai/r18n#total-flexibility).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ai/r18n/issues/155#issuecomment-336978627

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by mkaito** [comment]
Anyway, about DBLoader, seems like I just need to load a hash from the database. However, it does not seem to be documented what fields that hash needs to have, and what these fields need to contain. Is this data structure documented somewhere?

**Comment by ai** [comment]
@mkaito there is no `DBLoader` in PostCSS. It is just an example of flexibility, that you can write it.

Loaders API documented here https://github.com/ai/r18n/tree/master/r18n-core#loaders

You need to make a class with 2 methods: `available` and `load(locale)`

**Comment by AlexWayfer** [comment]
> @mkaito there is no DBLoader in PostCSS

@ai, are you okay? :disappointed_relieved:

**Comment by ai** [comment]
@AlexWayfer Imean that it is just example in docs. Not a real class, that we wrote.

**Comment by AlexWayfer** [comment]
@ai, yes, I understood. But **PostCSS** in **R18n** repository…

**Comment by ai** [comment]
@AlexWayfer Oops :D

**Comment by mkaito** [comment]
Yup, those were the sparse docs I referred to. I basically says to implement said methods. It does not say a word about what they need to return.

**Comment by AlexWayfer** [comment]
@mkaito I think that this can be (should be?) implemented in a separate gem.

**Comment by mkaito** [comment]
Maybe. But I just want to get my client an interface to edit all the strings that are currently in a yaml file. Putting them in the database would seem like the most straightforward way to do that, especially since the readme mentioned loading via ActiveRecord (although I use Sequel).

Oh well, maybe some other time. I'll just have to go over all the text manually with them.

**Comment by mkaito** [comment]
That sounds like something I should try. Thanks.
