### ISSUE TITLE
I18n.locale is wrong after I install this gem.

### ISSUE THREAD

**Issue by piya23300** [ai/r18n#163]
My rails version is 5.1.4 and `r18n` gem version is
```
r18n-core (2.2.0)
    r18n-rails (2.2.0)
      r18n-rails-api (= 2.2.0)
    r18n-rails-api (2.2.0)
      i18n
      r18n-core (= 2.2.0)
```

At `application.rb`

```
config.i18n.default_locale = :th
```

before I install `r18n` gem

```
puts I18n.locale => :th
```

after I installed `r18n` gem

```
puts I18n.locale => :"en-US"
```

Can you help me?

Thank you in advance.

**Comment by ai** [comment]
What files so you have in `config/locales` and `app/i18n`?

**Comment by piya23300** [comment]
I have 2 files at `config/locales`. `en.yml` and `th.yml`

**Comment by ai** [comment]
Strange. Where do you put `I18n.locale`? What do you have in `R18n.get`?

**Comment by piya23300** [comment]
Where do you put I18n.locale?

I put it at `console` (`rails console`).


What do you have in R18n.get?

I can call it. it returns a lot of data.

**Comment by ai** [comment]
Show me `R18n.get.code`

**Comment by piya23300** [comment]
```
#<R18n::Untranslated:0x007fbaf2251f70 @translated_path="", @untranslated_path="code", @locale=Locale en-US (American English), @filters=#<R18n::GlobalFilterList:0x007fbaefcf2a18>>
```

**Comment by ai** [comment]
What locale will you have in Rails controller in HTTP request from browser with `th` locale?

**Comment by piya23300** [comment]
I don't send any locale.

```
Started GET "/pet_cards/new" for 127.0.0.1 at 2017-12-23 17:57:40 +0700
Processing by PetCardsController#new as HTML
  Rendering pet_cards/new.html.slim within layouts/application
  Rendered pet_cards/_form.html.slim (17.2ms)
  Rendered pet_cards/new.html.slim within layouts/application (25.1ms)
Completed 200 OK in 690ms (Views: 43.8ms | ActiveRecord: 0.0ms)
```

**Comment by ai** [comment]
Put `I18n.locale` to your controller code or in your view file

**Comment by piya23300** [comment]
```
I18n.locale => en-US
18n.default_locale => th
```

**Comment by ai** [comment]
What `HTTP_ACCEPT_LANGUAGES` header do you have in your browser?

Maybe your can create small Rails project to reproduce the problem, do I will not ask you for many tests 😅?

**Comment by piya23300** [comment]
```
{"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff"}
```

I just create the project 1 week ago - -"

**Comment by piya23300** [comment]
my repo https://github.com/piya23300/hopet_r18n

**Comment by ai** [comment]
Here are two different problems:

1. Locale in `rails console`
2. Locale in controller during a web request.

Let’s fix the first one first. [Here is](https://github.com/ai/r18n/blob/eeeb4fa60c3e9293f10c712384bb9a8f82ac679c/r18n-rails/lib/r18n-rails.rb#L49-L60) current R18n locale choosing for `rails console`:

1. Take `ENV['LANG']`.
2. If `ENV['LANG']` is missed, use `I18n.default_locale`.

So, what is your operation system language? Show `puts ENV['LANG']`

**Comment by piya23300** [comment]
```
irb(main):001:0> ENV['LANG']
=> "en_US.UTF-8"
```

Oh, I see. >< but I think the gem should use `I18n.default_locale` the same rails to be a default locale.

http://guides.rubyonrails.org/i18n.html#configure-the-i18n-module
```
The I18n library will use English as a default locale, i.e. if a different locale is not set, :en will be used for looking up translations.
```

Thank you to help me and Happy New Year 2018 🎉🎉🎉

**Comment by ai** [comment]
Good question. R18n Rails is compatibility layout. But it is not 100% the same since it try to improve I18n 😊.

Because current R18n behavior is public API I can't change it without major version.

Do you really need  Rails behavior? I can give you small snippet to ignore ENV.

**Comment by piya23300** [comment]
Yes, I need it.

because I think gems shouldn't change the behavior of Rails configuration.

**Comment by ai** [comment]
Create `config/initializers/r18n_fix.rb` and put this code:

```ruby
ActiveSupport.on_load(:after_initialize) do
  locale = I18n.default_locale.to_s
  if defined? Rails::Console and not defined? Wirble
    i18n   = R18n::I18n.new(locale, R18n.default_places,
                            off_filters: :untranslated,
                            on_filters:  :untranslated_bash)
    R18n.set(i18n)
  else
    R18n.set(locale)
  end
end
```

it will remove `ENV` usage.

**Comment by piya23300** [comment]
Thank you so much.
