### ISSUE TITLE
`no` locale

### ISSUE THREAD

**Issue by AlexWayfer** [ai/r18n#166]
I think it doesn't exist (anymore).

https://github.com/TakahikoKawasaki/nv-i18n/issues/9

**Comment by ai** [comment]
What code is used for Norwegian in Rails I18n?

**Comment by AlexWayfer** [comment]
[`nb`](https://github.com/svenfuchs/rails-i18n/blob/dfc37a89285ba4de510affe6de5f5a79914fb67d/rails/locale/nb.yml) is for Bokmål and [`nn`](https://github.com/svenfuchs/rails-i18n/blob/dfc37a89285ba4de510affe6de5f5a79914fb67d/rails/locale/nn.yml) for Nynorsk. Contents of `nb` and `no` in this repo are the same.

**Comment by ai** [comment]
So, `no` is just a alias for `nb`? Let's do the same to keep API compatibility.

**Comment by AlexWayfer** [comment]
And [there is commit](https://github.com/svenfuchs/rails-i18n/commit/196ea80372e08941f9e9e8899e3af7b0b86e703c#diff-25099b7929778e13d340d4ba43fd4408).

**Comment by AlexWayfer** [comment]
> So, no is just a alias for nb? Let's do the same to keep API compatibility.

No, it's not an alias, `no-NB` moved to `nb` and `no-NN` moved to `nn`.
