### ISSUE TITLE
The need for `!!proc`

### ISSUE THREAD

**Issue by AlexWayfer** [ai/r18n#174]
Hello!

How much the `!!proc` is necessary? :grimacing: 

After #173 there is only one place in code with `eval`, and it's for `!!proc`. I know, this is almost the only way to implement it, but… What real-life task can not be done with custom filters and variables?

**Comment by ai** [comment]
Yeap, it is very dangerous filter and I never used it.

Let’s depreacte it in this minor version and then we will remove it in next major.

**Comment by AlexWayfer** [comment]
> Let’s depreacte it in this minor version and then we will remove it in next major.

Just curious: how useful are minor releases with deprecations instead of a good major release at once? Code was slightly refactored (thanks to RuboCop, maybe I'll also try to split huge methods), we can remove some dubious things and resolve some issues and push it as major. No?

**Comment by ai** [comment]
Done 745e1c6

**Comment by ai** [comment]
Released in 3.0
